In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

DATA_PATH = "data/customer_churn_1M.csv"

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
df.head()

Shape: (1000000, 32)

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,NaN,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [2]:
df.info()
df.describe(include="all").T

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   customer_id                  1000000 non-null  str
 1   signup_date                  1000000 non-null  str
 2   age                          1000000 non-null  int64
 3   gender                       1000000 non-null  str
 4   annual_income                970041 non-null   float64
 5   education                    1000000 non-null  str
 6   marital_status               1000000 non-null  str
 7   dependents                   1000000 non-null  int64
 8   tenure                       1000000 non-null  int64
 9   contract                     1000000 non-null  str
 10  payment_method               1000000 non-null  str
 11  paperless_billing            1000000 non-null  str
 12  senior_citizen               1000000 non-null  int64
 13  monthlycharges               1000000 non-null  float64
 14  totalcharges                 1000000 non-null  float64
 15  num_services                 1000000 non-null  int64
 16  has_phone_service            1000000 non-null  int64
 17  has_internet_service         1000000 non-null  int64
 18  has_online_security          1000000 non-null  int64
 19  has_online_backup            1000000 non-null  int64
 20  has_device_protection        1000000 non-null  int64
 21  has_tech_support             1000000 non-null  int64
 22  has_streaming_tv             1000000 non-null  int64
 23  has_streaming_movies         1000000 non-null  int64
 24  customer_satisfaction        980079 non-null   float64
 25  num_complaints               970094 non-null   float64
 26  num_service_calls            1000000 non-null  int64
 27  late_payments                1000000 non-null  int64
 28  avg_monthly_gb               949988 non-null   float64
 29  days_since_last_interaction  1000000 non-null  int64
 30  credit_score                 959605 non-null   float64
 31  churn                        1000000 non-null  int64
dtypes: float64(7), int64(17), str(8)
memory usage: 244.1 MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,1000000,1000000,CUST0000000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
signup_date,1000000,1000000,2022-12-12 12:53:58.199463,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,1000000.0,NaN,NaN,NaN,44.724603,14.479468,18.0,34.0,44.0,55.0,90.0
gender,1000000,3,Male,490166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
annual_income,970041.0,NaN,NaN,NaN,58788.311936,37137.433079,20000.0,32712.56,48954.6,73475.13,250000.0
education,1000000,5,bachelor,300324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital_status,1000000,4,married,450115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dependents,1000000.0,NaN,NaN,NaN,0.799831,0.893654,0.0,0.0,1.0,1.0,5.0
tenure,1000000.0,NaN,NaN,NaN,22.381923,20.073341,1.0,6.0,16.0,33.0,72.0
contract,1000000,3,one_year,550468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_method,1000000,4,credit_card,349706,NaN,NaN,NaN,NaN,NaN,NaN,NaN
paperless_billing,1000000,2,Yes,749880,NaN,NaN,NaN,NaN,NaN,NaN,NaN
senior_citizen,1000000.0,NaN,NaN,NaN,0.199511,0.399633,0.0,0.0,0.0,0.0,1.0
monthlycharges,1000000.0,NaN,NaN,NaN,86.443701,27.59243,20.0,70.49,85.48,100.68,854.95673
totalcharges,1000000.0,NaN,NaN,NaN,1837.321438,1803.721634,16.3,484.53,1249.75,2617.66,16252.861508
num_services,1000000.0,NaN,NaN,NaN,2.563721,1.41233,1.0,1.0,2.0,3.0,6.0
has_phone_service,1000000.0,NaN,NaN,NaN,0.769551,0.42112,0.0,1.0,1.0,1.0,1.0
has_internet_service,1000000.0,NaN,NaN,NaN,0.849742,0.357324,0.0,1.0,1.0,1.0,1.0
has_online_security,1000000.0,NaN,NaN,NaN,0.339468,0.473529,0.0,0.0,0.0,1.0,1.0
has_online_backup,1000000.0,NaN,NaN,NaN,0.425723,0.494452,0.0,0.0,0.0,1.0,1.0
has_device_protection,1000000.0,NaN,NaN,NaN,0.297082,0.456973,0.0,0.0,0.0,1.0,1.0
has_tech_support,1000000.0,NaN,NaN,NaN,0.497344,0.499993,0.0,0.0,0.0,1.0,1.0
has_streaming_tv,1000000.0,NaN,NaN,NaN,0.59999,0.4899,0.0,0.0,1.0,1.0,1.0
has_streaming_movies,1000000.0,NaN,NaN,NaN,0.549086,0.497585,0.0,0.0,1.0,1.0,1.0
customer_satisfaction,980079.0,NaN,NaN,NaN,6.15911,2.328287,1.0,4.0,7.0,8.0,9.0
num_complaints,970094.0,NaN,NaN,NaN,0.701667,0.838148,0.0,0.0,1.0,1.0,7.0
num_service_calls,1000000.0,NaN,NaN,NaN,1.760248,1.485677,0.0,1.0,1.0,3.0,12.0
late_payments,1000000.0,NaN,NaN,NaN,0.400969,0.633289,0.0,0.0,0.0,1.0,5.0
avg_monthly_gb,949988.0,NaN,NaN,NaN,39.095179,43.852564,0.0,12.84,27.77,51.23,557.824023
days_since_last_interaction,1000000.0,NaN,NaN,NaN,44.494191,44.922587,1.0,12.0,31.0,62.0,365.0
credit_score,959605.0,NaN,NaN,NaN,678.562134,87.642951,300.0,619.0,680.0,740.0,850.0
churn,1000000.0,NaN,NaN,NaN,0.099227,0.298967,0.0,0.0,0.0,0.0,1.0

In [3]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

avg_monthly_gb           50012
credit_score             40395
annual_income            29959
num_complaints           29906
customer_satisfaction    19921
dtype: int64